[tool.isort]
# https://github.com/PyCQA/isort/wiki/isort-Settings
profile = "black"
# will group `import x` and `from x import` of the same module.
force_sort_within_sections = true
known_first_party = [
    "custom_components.motioneye",
    "homeassistant",
    "tests",
]
forced_separate = [
    "tests",
]
combine_as_imports = true
default_section = "THIRDPARTY"


[tool.pytest.ini_options]
addopts = "-qq --timeout=9 --cov=custom_components.motioneye"
console_output_style = "count"
testpaths = [
  "tests",
]

[tool.coverage.run]
branch = false

[tool.coverage.report]
show_missing = true
fail_under = 100
